### ISSUE TITLE
As a user I would like to search for articles

### ISSUE THREAD

**Issue by msw1nkels** [msc365/msc365.github.io#2]
### Tasks
- [ ] Investigate search capabilities for Jekyll
- [ ] Implement search for articles in _posts
- [ ] Show a search box on home page
